/*
drop View dbo.vwc_HPREDID_IDGENERICO
go
-- IDGENERICO de cada Item de HPRED relacionado por el IDARTICULO
Create View dbo.vwc_HPREDID_IDGENERICO with schemabinding  
as  
 select a.NOPRESTACION, a.HPREDID, b.IDARTICULO, c.IDGENERICO  
 from dbo.HPRED a  
  join dbo.SER b on a.IDSERVICIO=b.IDSERVICIO   
  join dbo.IART c on b.IDARTICULO=c.IDARTICULO   
  join dbo.USVGS u on u.IDVARIABLE='IDINVARTNA'  
 where b.IDARTICULO<>u.DATO  
Create unique clustered index idx_vwc_HPREDID_IDGENERICO_pk on vwc_HPREDID_IDGENERICO(HPREDID) on HIGHTABLES
Create index idx_vwc_HPREDID_IDGENERICO_NOPRESTACION on vwc_HPREDID_IDGENERICO(NOPRESTACION,HPREDID) on HIGHTABLES
go

drop View dbo.vwc_HPRED_IMOVH_HPREDID
go
-- Todos los IMOVH que tienen HPREDID, claro está que podrian estar cruzados (infima posibilidad)  
Create View dbo.vwc_HPRED_IMOVH_HPREDID with schemabinding  
as  
 select a.NOPRESTACION, a.HPREDID, b1.IDARTICULO, c1.IDGENERICO, a1.IDITAR, CANTIDAD=sum(b1.CANTIDAD), CB=COUNT_BIG(*)   
 from dbo.HPRED a  
  join dbo.IMOV a1 on a.NOPRESTACION=a1.NOPRESTACION and a1.ESTADO='1'  
  join dbo.IMOVH b1 on a1.CNSMOV=b1.CNSMOV and a.HPREDID=b1.HPREDID and b1.CANTIDAD>0 and b1.ESTADO=1  
  join dbo.IART c1 on b1.IDARTICULO=c1.IDARTICULO  
  join dbo.USVGS u on u.IDVARIABLE='IDINVMOVPRE' and a1.IDTIPOMOV=u.DATO   
 group by a.NOPRESTACION, a.HPREDID, b1.IDARTICULO, c1.IDGENERICO, a1.IDITAR  
go
Create unique clustered index idx_vwc_HPRED_IMOVH_HPREDID_pk on vwc_HPRED_IMOVH_HPREDID(HPREDID,IDARTICULO) on HIGHTABLES
Create index idx_vwc_HPRED_IMOVH_HPREDID_NOPRESTACION on vwc_HPRED_IMOVH_HPREDID(NOPRESTACION,HPREDID) on HIGHTABLES
go

drop View dbo.vwc_Despachos_HPRED_xHPREDID
go
-- Despachos con su correspondiente HPREDID revalidado con el IDGENERICO  
Create View dbo.vwc_Despachos_HPRED_xHPREDID   
as  
 select a.*  
 from vwc_HPRED_IMOVH_HPREDID a with (/*noexpand,*/nolock)  
  join vwc_HPREDID_IDGENERICO b with (noexpand,nolock) on a.HPREDID=b.HPREDID and a.IDGENERICO=b.IDGENERICO  
go

drop View dbo.vwc_Despachos_HPRED_xIDGENERICO
go
-- Despachos sin su correspondiente HPREDID, se cruzan por NOPRESTACION y IDGENERICO  
Create View dbo.vwc_Despachos_HPRED_xIDGENERICO   
as  
 select a.*  
 from dbo.vwc_HPRED_IMOVH_HPREDID a with (/*noexpand,*/nolock)  
  join dbo.vwc_HPREDID_IDGENERICO b with (noexpand,nolock) on a.NOPRESTACION=b.NOPRESTACION and a.HPREDID<>b.HPREDID and a.IDGENERICO=b.IDGENERICO  
  left join dbo.vwc_Despachos_HPRED_xHPREDID c on a.HPREDID=c.HPREDID -- no deben existir aqui  
 where c.HPREDID is null  
go

drop function dbo.fnc_HPRED_xIDARTICULO_Despachado
go
-- Función que retorna los IDARTICULOS reales despachados, si por algun motivo no existe en IMOVH retorna el IDGENERICO del Servicio relacionado
Create function dbo.fnc_HPRED_xIDARTICULO_Despachado(@NOPRESTACION varchar(20), @IDSERVICIO varchar(20), @HPREDID bigint, @CANTIDAD int)  
returns @Tabla Table (  
 IDARTICULO varchar(20), CODCUM varchar(20), CANTIDAD int  
)   
as  
begin  
 declare   
  @Cantidad2 int;  
 insert into @Tabla  
 select d.IDARTICULO, e.CODCUM, cast(c.CANTIDAD as int)  
 from   
  dbo.SER b with (nolock)   
  left join dbo.vwc_Despachos_HPRED_xHPREDID s on s.HPREDID=@HPREDID  
  outer apply (select CANTIDAD=sum(g.CANTIDAD) from dbo.vwc_Despachos_HPRED_xHPREDID g where g.HPREDID=@HPREDID) g  
  left join dbo.vwc_Despachos_HPRED_xIDGENERICO s2 on s2.NOPRESTACION=@NOPRESTACION   
  outer apply (select CANTIDAD=sum(g2.CANTIDAD) from dbo.vwc_Despachos_HPRED_xIDGENERICO g2 where g2.NOPRESTACION=@NOPRESTACION) g2    
  cross apply (  
   select CANTIDAD=case when s.CANTIDAD is null and s2.CANTIDAD is null then @CANTIDAD else   
    case when coalesce(s.CANTIDAD,0)>0 then (s.CANTIDAD/g.CANTIDAD)*@CANTIDAD else (s2.CANTIDAD/g2.CANTIDAD)*@CANTIDAD end  
   end  
  ) c  
  cross apply (select IDARTICULO=coalesce(coalesce(s.IDARTICULO,s2.IDARTICULO),b.IDARTICULO)) d  
  left join IART e with (nolock) on d.IDARTICULO=e.IDARTICULO  
 where b.IDSERVICIO=@IDSERVICIO  
  
 -- Ajuste por decimales  
 select @Cantidad2=sum(CANTIDAD) from @Tabla  
 update top (1) @Tabla set CANTIDAD += @CANTIDAD - @Cantidad2  
  
 return;  
end  
go
*/

drop View [dbo].[vwRIPS_HPRED_SER_1] 
go
Create View [dbo].[vwRIPS_HPRED_SER_1] 
with schemabinding
as 
	SELECT 'HPRED' AS TABLA,HPRED.HPREDID PRESTACIONID,CONSECUTIVO=HPRE.NOPRESTACION,HPRED.NOITEM AS ITEM,SER.CODIGORIPS,RENCP.ARCHIVO AS ARCHIVORIPS,
		0 AS PYP,HPRED.IDTERCEROCA AS IDCONTRATANTE,HPRED.IDPLAN,HPRED.N_FACTURA,AFI.IDAFILIADO,AFI.TIPO_DOC,AFI.DOCIDAFILIADO,
		HPRE.FECHA,HADM.FECHA AS FINGRESO, HADM.FECHAALTA AS FEGRESO,HPRED.IDSERVICIO,SER.IDALTERNA,
		SER.TIPOMED,LEFT(coalesce(SER.DESCSERVICIOCUPS,SER.DESCSERVICIO),60) AS DESCSERVICIO, LEFT(SER.NOM_GENERICO,60) AS NOMGENERICO,
		HADM.VIAINGRESO, HADM.DXEGRESO AS IDDX, 2 AS TIPODX,
		HADM.DXEGRESO AS DXSALIDA,HADM.DXSALIDA1 AS DXR1,HADM.DXSALIDA2 AS DXR2,HADM.DXSALIDA3 AS DXR3, HADM.COMPLICACION AS COMPLICACION, '' AS FORMAREALIZACION, 
		HADM.CAUSABMUERTE AS CAUSAMUERTE, HADM.DESTINO AS DESTINO, HADM.ESTADOPSALIDA AS ESTADOSALIDA, 
		CAST(ROUND(abs(COALESCE(HPRED.CANTIDAD,1)),0) AS INT) AS CANTIDAD, 
		round(CAST(abs(COALESCE(HPRED.VALOR,0)) AS DECIMAL(15,2)),0) AS VALOR, round(CAST(abs(COALESCE(HPRED.VALORCOPAGO,0)) AS DECIMAL(15,2)),0) AS VALORCOPAGO, 
		round(CAST(abs(COALESCE(HPRED.VALOR,0))*abs(COALESCE(HPRED.CANTIDAD,1)) AS DECIMAL(15,2)),0) AS VALORITEM, 
		round(CAST(abs((COALESCE(HPRED.VALOR,0)*COALESCE(HPRED.CANTIDAD,1))-COALESCE(HPRED.VALORCOPAGO,0)) AS DECIMAL(15,2)),0) AS VRNETO,
		CIRUGIA=0,HPRED.IDCIRUGIA,HPRED.CONSECUTIVOCX,HPRED.KCNTRID,HPRED.KCNTID, HPRE.IDSEDE,
		SER.PREFIJO, SER.IDARTICULO, HPRE.IDMEDICO, HADM.TIPOTTEC, HADM.CAUSAEXTERNA, HPRE.TIPOPRESTACION, 
		HADM.NOAUTORIZACION, HPRE.NUMAUTORIZA, HPRED_NOAUTORIZACION=HPRED.NOAUTORIZACION, HPRE.AMBITO, HADM.DXINGRESO, SER.IDCUM, HADM.NOADMISION
	FROM dbo.HADM 
		JOIN dbo.HPRE  ON HADM.NOADMISION    = HPRE.NOADMISION and HPRE.TIPOPRESTACION = 0 AND (HPRE.CIRUGIA is null or HPRE.CIRUGIA<>'Si')
		JOIN dbo.HPRED ON HPRED.NOPRESTACION = HPRE.NOPRESTACION  /*AND HPRED.VALOR > 0 */ 		
		JOIN dbo.AFI   ON AFI.IDAFILIADO     = HADM.IDAFILIADO 
		JOIN dbo.SER   ON SER.IDSERVICIO     = HPRED.IDSERVICIO
		JOIN dbo.RENCP ON RENCP.IDCONCEPTORIPS = SER.CODIGORIPS 
	WHERE 
		(HADM.CLASENOPROC is null or HADM.CLASENOPROC<>'NP')	-- Excluye los No procesar
		AND NOT (RENCP.ARCHIVO in ('AH','AU') AND HADM.CLASEING<>'A') -- Excluye las que no son del Modulo Hospitalario para AH y AU
		-- AND ( HADM.CLASEING='A' or (HADM.CLASEING<>'A' and RENCP.ARCHIVO<>'AH' and RENCP.ARCHIVO<>'AU') ) -- Excluye las que no son del Modulo Hospitalario para AH y AU
go

/* YA no se ueden usar desde que se pasó Inventario a DOXA

drop index vwRIPS_HPRED_SER_1.idx_vwRIPS_HPRED_SER_1_PK
go
CREATE UNIQUE CLUSTERED INDEX idx_vwRIPS_HPRED_SER_1_PK ON [dbo].[vwRIPS_HPRED_SER_1](NOADMISION,PRESTACIONID)
WITH (SORT_IN_TEMPDB = OFF) ON [HIGHTABLES]
GO
drop index vwRIPS_HPRED_SER_1.idx_vwRIPS_HPRED_SER_1_Evento 
go
CREATE NONCLUSTERED INDEX idx_vwRIPS_HPRED_SER_1_Evento ON [dbo].[vwRIPS_HPRED_SER_1] (ARCHIVORIPS)
INCLUDE ([CONSECUTIVO],[ITEM],[CODIGORIPS],[IDCONTRATANTE],[N_FACTURA],[IDAFILIADO],[TIPO_DOC],[DOCIDAFILIADO],[FECHA],[FINGRESO],[FEGRESO],[IDALTERNA],[IDDX],[TIPODX],[DXR1],[DXR2],[DXR3],[FORMAREALIZACION],[CANTIDAD],[VALOR],[VALORCOPAGO],[VALORITEM],[VRNETO],[PREFIJO],[IDARTICULO],[TIPOTTEC],[CAUSAEXTERNA],[NOAUTORIZACION],[NUMAUTORIZA],[HPRED_NOAUTORIZACION],[AMBITO],[DXINGRESO])
WITH (SORT_IN_TEMPDB = OFF, ONLINE = ON) ON [HIGHTABLES]
GO
CREATE NONCLUSTERED INDEX idx_vwRIPS_HPRED_SER_1_Capita ON [dbo].[vwRIPS_HPRED_SER_1] (ARCHIVORIPS,IDCONTRATANTE,KCNTID,FECHA)
WITH (SORT_IN_TEMPDB = OFF, ONLINE = ON) ON [HIGHTABLES]
GO
CREATE NONCLUSTERED INDEX idx_vwRIPS_HPRED_SER_1_N_FACTURA ON [dbo].[vwRIPS_HPRED_SER_1] ([N_FACTURA])
WITH (SORT_IN_TEMPDB = OFF, ONLINE = ON) ON [HIGHTABLES]
GO

CREATE NONCLUSTERED INDEX idx_vwRIPS_HPRED_SER_1_Capita2
ON [dbo].[vwRIPS_HPRED_SER_1] ([ARCHIVORIPS],[IDCONTRATANTE],[KCNTID],[FECHA])
INCLUDE ([CONSECUTIVO],[ITEM],[CODIGORIPS],[N_FACTURA],[IDAFILIADO],[TIPO_DOC],[DOCIDAFILIADO],[FINGRESO],[FEGRESO],[IDALTERNA],[IDDX],[TIPODX],[DXR1],[DXR2],[DXR3],[FORMAREALIZACION],[CANTIDAD],[VALOR],[VALORCOPAGO],[VALORITEM],[VRNETO],[PREFIJO],[IDARTICULO],[TIPOTTEC],[CAUSAEXTERNA],[NOAUTORIZACION],[NUMAUTORIZA],[HPRED_NOAUTORIZACION],[AMBITO],[DXINGRESO])
WITH (SORT_IN_TEMPDB = ON, ONLINE = ON) ON [HIGHTABLES]

CREATE NONCLUSTERED INDEX idx_vwRIPS_HPRED_SER_1_Capita3
ON [dbo].[vwRIPS_HPRED_SER_1] ([ARCHIVORIPS],[IDCONTRATANTE],[KCNTID],[FECHA])
INCLUDE ([CONSECUTIVO],[ITEM],[CODIGORIPS],[N_FACTURA],[IDAFILIADO],[TIPO_DOC],[DOCIDAFILIADO],[IDSERVICIO],[TIPOMED],[DESCSERVICIO],[FORMAREALIZACION],[CANTIDAD],[VALOR],[VALORCOPAGO],[VALORITEM],[VRNETO],[TIPOTTEC],[NOAUTORIZACION],[NUMAUTORIZA],[HPRED_NOAUTORIZACION],[AMBITO],[IDCUM])
WITH (SORT_IN_TEMPDB = ON, ONLINE = ON) ON [HIGHTABLES]

CREATE NONCLUSTERED INDEX idx_HADM_Capita
ON [dbo].[HADM] ([IDTERCERO],[KCNTID],[FECHA])
INCLUDE ([IDAFILIADO],[TIPOADM],[NOAUTORIZACION],[FECHAALTA],[N_FACTURA],[CERRADA],[CLASENOPROC],[CLASEING],[TIPOTTEC])
WITH (SORT_IN_TEMPDB = ON, ONLINE = ON) ON [HIGHTABLES]

CREATE NONCLUSTERED INDEX idx_vwRIPS_HPRED_SER_1_Capita4
ON [dbo].[vwRIPS_HPRED_SER_1] ([ARCHIVORIPS],[IDCONTRATANTE],[KCNTID],[FECHA])
INCLUDE ([CONSECUTIVO],[ITEM],[CODIGORIPS],[N_FACTURA],[IDAFILIADO],[TIPO_DOC],[DOCIDAFILIADO],[IDALTERNA],[CANTIDAD],[VALOR],[VALORCOPAGO],[VALORITEM],[VRNETO],[PREFIJO],[IDARTICULO],[IDMEDICO],[TIPOTTEC],[NOAUTORIZACION],[NUMAUTORIZA],[HPRED_NOAUTORIZACION],[AMBITO])
WITH (SORT_IN_TEMPDB = ON, ONLINE = ON) ON [HIGHTABLES]
GO
*/

create nonclustered index idx_RENCP_ARCHIVO on RENCP (ARCHIVO) include (IDCONCEPTORIPS,DESCRIPRIPS)
go

drop index RENR.idx_RENR_RIPS
go
CREATE NONCLUSTERED INDEX idx_RENR_RIPS ON [dbo].[RENR] ([ARCHIVORIPS])
INCLUDE ([TABLA],[CONSECUTIVO],[ITEM],[CONCEPTORIPS],[N_FACTURA],[TIPO_DOC],[DOCIDAFILIADO],[FECHA],[FINGRESO],[NOAUTORIZACION],[FEGRESO],[IDSERVICIO],[TIPO],[NOMGENERICO],[FORMA],[CONCENTRACION],[UMEDIDA],[CANTIDAD],[AMBITO],[FINALIDAD],[VIAINGRESO],[PERSONALAT],[IDDX],[TIPODX],[DXSALIDA],[DXR1],[DXR2],[DX3],[COMPLICACION],[FORMAREALIZACION],[CAUSAEXT],[CAUSAMUERTE],[DESTINO],[ESTADOSALIDA],[VALOR],[VALORITEM],[VALORCOPAGO],[VRNETO],[IDAFILIADO],[CAPITADO],[CIRUGIA],[PRESTACIONID])
WITH (SORT_IN_TEMPDB = ON, ONLINE = ON) ON [HIGHTABLES]
GO
CREATE NONCLUSTERED INDEX idx_RENR_N_FACTURA ON [dbo].[RENR] ([ARCHIVORIPS],[N_FACTURA])
INCLUDE ([TABLA],[CONSECUTIVO],[ITEM],[CONCEPTORIPS],[TIPO_DOC],[DOCIDAFILIADO],[FECHA],[FINGRESO],[NOAUTORIZACION],[FEGRESO],[IDSERVICIO],[TIPO],[NOMGENERICO],[FORMA],[CONCENTRACION],[UMEDIDA],[CANTIDAD],[AMBITO],[FINALIDAD],[VIAINGRESO],[PERSONALAT],[IDDX],[TIPODX],[DXSALIDA],[DXR1],[DXR2],[DX3],[COMPLICACION],[FORMAREALIZACION],[CAUSAEXT],[CAUSAMUERTE],[DESTINO],[ESTADOSALIDA],[VALOR],[VALORITEM],[VALORCOPAGO],[VRNETO],[IDAFILIADO],[CAPITADO],[CIRUGIA],[PRESTACIONID])
WITH (SORT_IN_TEMPDB = ON, ONLINE = ON) ON [HIGHTABLES]
GO

CREATE NONCLUSTERED INDEX idx_RENRAF_N_FACTURA ON [dbo].[RENRAF] ([N_FACTURA])
INCLUDE ([FECHAINICIO],[FECHAFINAL],[VALORCOPAGO],[VALORCOMISION],[VALORDESCUENTO],[VALORNETO])
WITH (SORT_IN_TEMPDB = ON, ONLINE = ON) ON [HIGHTABLES]
GO

drop index HADM.idx_HADM_CLASENOPROC_NOADMISION 
go
create nonclustered index idx_HADM_CLASENOPROC_NOADMISION on HADM (NOADMISION,CLASENOPROC)
include (FECHA,FECHAALTA,VIAINGRESO,DXEGRESO,DXSALIDA1,DXSALIDA2,DXSALIDA3,COMPLICACION,CAUSABMUERTE,DESTINO,ESTADOPSALIDA,TIPOTTEC,
	CAUSAEXTERNA,NOAUTORIZACION,DXINGRESO)
WITH (SORT_IN_TEMPDB = OFF, ONLINE = ON) ON [HIGHTABLES]
GO

CREATE NONCLUSTERED INDEX idx_IMOV_2 ON [dbo].[IMOV] ([IDTIPOMOV],[ESTADO],[NOPRESTACION],[PROCEDENCIA])
WITH (SORT_IN_TEMPDB = ON, ONLINE = ON) ON [HIGHTABLES]
GO

CREATE NONCLUSTERED INDEX [idx_HPRED_HPREDID] ON [dbo].[HPRED]([HPREDID] ASC) INCLUDE([NOPRESTACION],[NOITEM],[IDSERVICIO],[CANTIDAD],[VALOR],[VALORCOPAGO]) 
WITH (SORT_IN_TEMPDB = ON, ONLINE = ON) ON [HIGHTABLES]
GO


drop View [dbo].[vwRIPS_HPRED_SER] 
go
-- Todos los Clientes
Create View [dbo].[vwRIPS_HPRED_SER] 
as 
	SELECT 'HPRED' AS TABLA,a.PRESTACIONID,a.CONSECUTIVO,a.ITEM,a.CODIGORIPS,a.ARCHIVORIPS,
		0 AS PYP,FTR.IDTERCERO AS IDTERCEROFACT,a.IDCONTRATANTE,a.IDPLAN,a.N_FACTURA,a.IDAFILIADO,a.TIPO_DOC,a.DOCIDAFILIADO,
		a.FECHA,a.FECHA AS FINGRESO,na.NUMAUTORIZA as NUMAUTORIZA, a.FEGRESO,a.IDSERVICIO,a.IDALTERNA,
		a.TIPOMED,ts.TIPOSERVICIO as TIPOSERVICIO,	a.DESCSERVICIO, a.NOMGENERICO,
		IFFA.DESCRIPCION AS FORMA,ICCN.DESCRIPCION AS CONCENTRACION,IUNI.DESCRIPCION AS UMEDIDA,
		am.AMBITO AS AMBITO, PRE.FINALIDAD, a.VIAINGRESO, MES.PERSONAL_AT AS PERSONALAT, 
		dx.IDDX, a.TIPODX, DXSALIDA=coalesce(a.DXSALIDA,h.IDDX), DXR1=coalesce(a.DXR1,h.DX1), DXR2=coalesce(a.DXR2,h.DX2), DXR3=coalesce(a.DXR3,h.DX3),
		a.COMPLICACION AS COMPLICACION, a.FORMAREALIZACION, 
		ce.CAUSAEXT AS CAUSAEXT, a.CAUSAMUERTE, a.DESTINO AS DESTINO, a.ESTADOSALIDA, 
		a.CANTIDAD, a.VALOR, a.VALORCOPAGO, a.VALORITEM, a.VRNETO, FTR.ESTADO AS ESTADOFACTURA,CAPITADO=coalesce(KCNT.CAPITA,0),CIRUGIA=0,a.IDCIRUGIA,
		a.CONSECUTIVOCX, a.KCNTRID, a.KCNTID, ttec.TIPOSISTEMA, a.IDSEDE, FTR.TIPOFIN, a.NOADMISION
	FROM [vwRIPS_HPRED_SER_1] a with (nolock/*,noexpand*/)
		LEFT JOIN  dbo.FTR with (nolock)  ON FTR.N_FACTURA = a.N_FACTURA
		LEFT JOIN dbo.PRE with (nolock)  ON PRE.PREFIJO = a.PREFIJO
		LEFT JOIN dbo.MED with (nolock)  ON MED.IDMEDICO = a.IDMEDICO
		LEFT JOIN dbo.MES with (nolock)  ON MES.IDEMEDICA = MED.IDEMEDICA
		LEFT JOIN dbo.IART with (nolock) ON IART.IDARTICULO = a.IDARTICULO
		LEFT JOIN dbo.IFFA with (nolock) ON IFFA.IDFORFARM = IART.IDFORFARM
		LEFT JOIN dbo.ICCN with (nolock) ON ICCN.IDCONCENTRA= IART.IDCONCENTRA
		LEFT JOIN dbo.IUNI with (nolock) ON IUNI.IDUNIDAD = IART.IDUNIDAD
		left join dbo.TTEC with (nolock) on a.TIPOTTEC=TTEC.TIPO
		left join dbo.KCNT with (nolock) on a.KCNTID=KCNT.KCNTID
		outer apply (
			SELECT top 1 hc.IDDX, hc.TIPODX, hc.FINALIDAD, hc.DX1, hc.DX2, hc.DX3, hc.CAUSAEXT, b.DESCRIPCION  
			FROM dbo.HCA hc with (nolock)  
				JOIN dbo.MDX b with (nolock) ON hc.IDDX = b.IDDX  
			where hc.IDAFILIADO=a.IDAFILIADO and hc.FECHA>=a.FINGRESO and hc.FECHA<=a.FEGRESO  
			order by hc.FECHA desc
		) h
		cross apply (
			Select CAUSAEXT = 
				case when coalesce(a.CAUSAEXTERNA,'')='' then 
					case when coalesce(h.CAUSAEXT,'') ='' then '13' else h.CAUSAEXT end 
				else a.CAUSAEXTERNA end
		) ce
		cross apply (
			select IDDX = 
				case when coalesce(a.IDDX,'')='' then 
					case when coalesce(h.IDDX,'')='' then 			
						coalesce(a.DXINGRESO,'')
					else h.IDDX end
				else a.IDDX end
		) dx
		cross apply (
			select NUMAUTORIZA = 
			case when coalesce(a.HPRED_NOAUTORIZACION,'')<>'' then a.HPRED_NOAUTORIZACION else 
				case when coalesce(a.NUMAUTORIZA,'')='' then a.NOAUTORIZACION else a.NUMAUTORIZA end 
			end
		) na 
		cross apply (Select TIPOSERVICIO = 	CASE a.CODIGORIPS    
				WHEN '06' THEN '3'  WHEN '07' THEN '4'	WHEN '08' THEN '3'  WHEN '09' THEN '1'      
				WHEN '10' THEN '1'  WHEN '11' THEN '1'	WHEN '14' THEN '2'	else '1' END) ts
		cross apply (Select AMBITO = CASE when coalesce(ltrim(rtrim(a.AMBITO)),'') = '' THEN '2' ELSE a.AMBITO END) am

	where a.ARCHIVORIPS<>'AM'

	union all

	-- Medicamentos cruzados con vwc_HPRED_IMOVH_Devoluciones para buscar el entregado de marca y no el generico
	SELECT 'HPRED' AS TABLA,a.PRESTACIONID,a.CONSECUTIVO,a.ITEM,a.CODIGORIPS,a.ARCHIVORIPS,
		0 AS PYP,FTR.IDTERCERO AS IDTERCEROFACT,a.IDCONTRATANTE,a.IDPLAN,a.N_FACTURA,a.IDAFILIADO,a.TIPO_DOC,a.DOCIDAFILIADO,
		a.FECHA,a.FECHA AS FINGRESO,na.NUMAUTORIZA as NUMAUTORIZA, a.FEGRESO, a.IDSERVICIO, 
		IDALTERNA = case when coalesce(b.CODCUM,'')='' then a.IDCUM else b.CODCUM end,
		a.TIPOMED,ts.TIPOSERVICIO as TIPOSERVICIO,	a.DESCSERVICIO, a.NOMGENERICO,
		IFFA.DESCRIPCION AS FORMA,ICCN.DESCRIPCION AS CONCENTRACION,IUNI.DESCRIPCION AS UMEDIDA,
		am.AMBITO AS AMBITO, PRE.FINALIDAD, a.VIAINGRESO, MES.PERSONAL_AT AS PERSONALAT, 
		dx.IDDX, a.TIPODX, DXSALIDA=coalesce(a.DXSALIDA,h.IDDX), DXR1=coalesce(a.DXR1,h.DX1), DXR2=coalesce(a.DXR2,h.DX2), DXR3=coalesce(a.DXR3,h.DX3),		
		a.COMPLICACION AS COMPLICACION, a.FORMAREALIZACION, 
		ce.CAUSAEXT AS CAUSAEXT, a.CAUSAMUERTE, a.DESTINO AS DESTINO, a.ESTADOSALIDA, 
		b.CANTIDAD, 
		VALOR = a.VALOR, --cast((a.VALOR/a.CANTIDAD)*b.CANTIDAD as decimal(14,0)), 
		VALORCOPAGO = cast((a.VALORCOPAGO/a.CANTIDAD)*b.CANTIDAD as decimal(14,0)),
		VALORITEM = cast((a.VALORITEM/a.CANTIDAD)*b.CANTIDAD as decimal(14,0)), 
		VRNETO = cast((a.VRNETO/a.CANTIDAD)*b.CANTIDAD as decimal(14,0)), 
		FTR.ESTADO AS ESTADOFACTURA,CAPITADO=coalesce(KCNT.CAPITA,0),CIRUGIA=0,a.IDCIRUGIA,
		a.CONSECUTIVOCX, a.KCNTRID, a.KCNTID, ttec.TIPOSISTEMA, a.IDSEDE, FTR.TIPOFIN, a.NOADMISION
	FROM [vwRIPS_HPRED_SER_1] a with (nolock/*,noexpand*/)
		LEFT JOIN  dbo.FTR with (nolock) ON FTR.N_FACTURA = a.N_FACTURA
		--left join dbo.vwc_HPRED_IMOVH_Devoluciones b with (nolock) ON b.HPREDID = a.PRESTACIONID
		outer apply dbo.fnc_HPRED_xIDARTICULO_Despachado(a.CONSECUTIVO,a.IDSERVICIO,a.PRESTACIONID,a.CANTIDAD) b
		LEFT JOIN dbo.PRE with (nolock) ON PRE.PREFIJO = a.PREFIJO
		LEFT JOIN dbo.MED with (nolock) ON MED.IDMEDICO = a.IDMEDICO
		LEFT JOIN dbo.MES with (nolock)  ON MES.IDEMEDICA = MED.IDEMEDICA
		LEFT JOIN dbo.IART with (nolock) ON IART.IDARTICULO = b.IDARTICULO
		LEFT JOIN dbo.IFFA with (nolock) ON IFFA.IDFORFARM  = IART.IDFORFARM
		LEFT JOIN dbo.ICCN with (nolock) ON ICCN.IDCONCENTRA= IART.IDCONCENTRA
		LEFT JOIN dbo.IUNI with (nolock) ON IUNI.IDUNIDAD = IART.IDUNIDAD
		left join dbo.TTEC with (nolock) on a.TIPOTTEC=TTEC.TIPO
		left join dbo.KCNT with (nolock) on a.KCNTID=KCNT.KCNTID
		outer apply (
			SELECT top 1 hc.IDDX, hc.TIPODX, hc.FINALIDAD, hc.DX1, hc.DX2, hc.DX3, hc.CAUSAEXT, b.DESCRIPCION  
			FROM dbo.HCA hc with (nolock)  
				JOIN dbo.MDX b with (nolock) ON hc.IDDX = b.IDDX  
			where hc.IDAFILIADO=a.IDAFILIADO and hc.FECHA>=a.FINGRESO and hc.FECHA<=a.FEGRESO  
			order by hc.FECHA desc
		) h
		cross apply (
			select IDDX = 
				case when coalesce(a.IDDX,'')='' then 
					case when coalesce(h.IDDX,'')='' then 			
						coalesce(a.DXINGRESO,'')
					else h.IDDX end
				else a.IDDX end
		) dx
		cross apply (Select CAUSAEXT = CASE a.CAUSAEXTERNA WHEN NULL THEN '13' WHEN '' THEN '13'	ELSE a.CAUSAEXTERNA END) ce
				cross apply (
			select NUMAUTORIZA = 
			case when coalesce(a.HPRED_NOAUTORIZACION,'')<>'' then a.HPRED_NOAUTORIZACION else 
				case when coalesce(a.NUMAUTORIZA,'')='' then a.NOAUTORIZACION else a.NUMAUTORIZA end 
			end
		) na  
		cross apply (Select TIPOSERVICIO = 	CASE a.CODIGORIPS    
				WHEN '06' THEN '3'  WHEN '07' THEN '4'	WHEN '08' THEN '3'  WHEN '09' THEN '1'      
				WHEN '10' THEN '1'  WHEN '11' THEN '1'	WHEN '14' THEN '2'	else '1' END) ts
		cross apply (Select AMBITO = CASE when coalesce(ltrim(rtrim(a.AMBITO)),'') = '' THEN '2' ELSE a.AMBITO END) am
	where a.ARCHIVORIPS='AM' and coalesce(a.CANTIDAD,0)>0 and coalesce(b.CANTIDAD,0)>0
go




