drop view [dbo].[vwa_HADM]
go
Create View [dbo].[vwa_HADM] -- with schemabinding    
as    
 SELECT A.NOADMISION, A.IDAFILIADO, A.FECHA, A.CLASEING, A.IDPLAN, A.IDTERCERO, A.TIPOADM, C.DESCRIPCION, A.HABCAMA, A.VIAINGRESO, A.DXINGRESO, A.FECHAVCEAUT, A.FECHAALTA, A.RESPCUENTA,     
  A.IDMEDICOTRA, A.FACTURADA, A.N_FACTURA, A.CERRADA, A.USUARIO, A.TIPOPOLIZA, A.FACTURABLE, A.COPAGO, A.COPAGONOAUTORIZACION, A.COPAGOVALOR, A.VFACTURAS,     
  A.DESCUENTO, A.TIPODTO, A.USUARIOALTA, A.TIPOCREDITO, A.CREDITO, A.MARCA, A.VENCEAUT, A.MTOPE, A.TIPOTOPE, A.FECHATOPE, A.VALORTOPE, A.TOPEOTROTERCERO,     
  A.IDAREA_ALTA, A.CLASENOPROC, A.LIQESTANCIA, A.FACTURADAPARCIAL, A.CNSHACTRAN, A.IDAREAINGRESO, A.IDAREAACTUAL, B.PAPELLIDO, B.SAPELLIDO,     
  B.PNOMBRE, B.SNOMBRE, B.TIPO_DOC, B.DOCIDAFILIADO, B.IDALTERNA, B.IDAFILIADOPPAL, B.CIUDAD, B.ZONA, B.IDSEDE, B.IDPROVEEDOR, B.IDADMINISTRADORA, B.NUMCARNET     
 FROM  dbo.HADM A     
  join dbo.afi B on A.IDAFILIADO=B.IDAFILIADO     
  join dbo.HTAD C on a.TIPOADM=C.TIPOADM      
 WHERE ( (CERRADA >=0 and CERRADA<= 2) )     
-- ORDER BY  A.CERRADA,  A.NOADMISION DESC    
go

drop View [dbo].[vwRIPS_HPRED_SER_1]
go
Create View [dbo].[vwRIPS_HPRED_SER_1]   
-- with schemabinding  
as   
 SELECT 'HPRED' AS TABLA,HPRED.HPREDID PRESTACIONID,CONSECUTIVO=HPRE.NOPRESTACION,HPRED.NOITEM AS ITEM,SER.CODIGORIPS,RENCP.ARCHIVO AS ARCHIVORIPS,  
  0 AS PYP,HPRED.IDTERCEROCA AS IDCONTRATANTE,HPRED.IDPLAN,HPRED.N_FACTURA,AFI.IDAFILIADO,AFI.TIPO_DOC,AFI.DOCIDAFILIADO,  
  HPRE.FECHA,HADM.FECHA AS FINGRESO, HADM.FECHAALTA AS FEGRESO,HPRED.IDSERVICIO,SER.IDALTERNA,  
  SER.TIPOMED,LEFT(coalesce(SER.DESCSERVICIOCUPS,SER.DESCSERVICIO),60) AS DESCSERVICIO, LEFT(SER.NOM_GENERICO,60) AS NOMGENERICO,  
  HADM.VIAINGRESO, HADM.DXEGRESO AS IDDX, 2 AS TIPODX,  
  HADM.DXEGRESO AS DXSALIDA,HADM.DXSALIDA1 AS DXR1,HADM.DXSALIDA2 AS DXR2,HADM.DXSALIDA3 AS DXR3, HADM.COMPLICACION AS COMPLICACION, '' AS FORMAREALIZACION,   
  HADM.CAUSABMUERTE AS CAUSAMUERTE, HADM.DESTINO AS DESTINO, HADM.ESTADOPSALIDA AS ESTADOSALIDA,   
  CAST(ROUND(abs(COALESCE(HPRED.CANTIDAD,1)),0) AS INT) AS CANTIDAD,   
  round(CAST(abs(COALESCE(HPRED.VALOR,0)) AS DECIMAL(15,2)),0) AS VALOR, round(CAST(abs(COALESCE(HPRED.VALORCOPAGO,0)) AS DECIMAL(15,2)),0) AS VALORCOPAGO,   
  round(CAST(abs(COALESCE(HPRED.VALOR,0))*abs(COALESCE(HPRED.CANTIDAD,1)) AS DECIMAL(15,2)),0) AS VALORITEM,   
  round(CAST(abs((COALESCE(HPRED.VALOR,0)*COALESCE(HPRED.CANTIDAD,1))-COALESCE(HPRED.VALORCOPAGO,0)) AS DECIMAL(15,2)),0) AS VRNETO,  
  CIRUGIA=0,HPRED.IDCIRUGIA,HPRED.CONSECUTIVOCX,HPRED.KCNTRID,HPRED.KCNTID, HPRE.IDSEDE,  
  SER.PREFIJO, SER.IDARTICULO, HPRE.IDMEDICO, HADM.TIPOTTEC, HADM.CAUSAEXTERNA, HPRE.TIPOPRESTACION,   
  HADM.NOAUTORIZACION, HPRE.NUMAUTORIZA, HPRED_NOAUTORIZACION=HPRED.NOAUTORIZACION, HPRE.AMBITO, HADM.DXINGRESO, SER.IDCUM, HADM.NOADMISION  
 FROM dbo.HADM   
  JOIN dbo.HPRE  ON HADM.NOADMISION    = HPRE.NOADMISION and HPRE.TIPOPRESTACION = 0 AND (HPRE.CIRUGIA is null or HPRE.CIRUGIA<>'Si')  
  JOIN dbo.HPRED ON HPRED.NOPRESTACION = HPRE.NOPRESTACION  /*AND HPRED.VALOR > 0 */     
  JOIN dbo.AFI   ON AFI.IDAFILIADO     = HADM.IDAFILIADO   
  JOIN dbo.SER   ON SER.IDSERVICIO     = HPRED.IDSERVICIO  
  JOIN dbo.RENCP ON RENCP.IDCONCEPTORIPS = SER.CODIGORIPS   
 WHERE   
  (HADM.CLASENOPROC is null or HADM.CLASENOPROC<>'NP') -- Excluye los No procesar  
  AND NOT (RENCP.ARCHIVO in ('AH','AU') AND HADM.CLASEING<>'A') -- Excluye las que no son del Modulo Hospitalario para AH y AU  
  -- AND ( HADM.CLASEING='A' or (HADM.CLASEING<>'A' and RENCP.ARCHIVO<>'AH' and RENCP.ARCHIVO<>'AU') ) -- Excluye las que no son del Modulo Hospitalario para AH y AU  
go


drop view [dbo].[vwRIPS_HPRED_SER_1_2]           
go
CREATE View [dbo].[vwRIPS_HPRED_SER_1_2]           
-- with schemabinding          
as           
 SELECT 'HPRED' AS TABLA,HPRED.HPREDID PRESTACIONID,CONSECUTIVO=HPRE.NOPRESTACION,HPRED.NOITEM AS ITEM,SER.CODIGORIPS,RENCP.ARCHIVO AS ARCHIVORIPS,          
  0 AS PYP,HPRED.IDTERCEROCA AS IDCONTRATANTE,HPRED.IDPLAN,HPRED.N_FACTURA,AFI.IDAFILIADO,AFI.TIPO_DOC,AFI.DOCIDAFILIADO,          
  HPRE.FECHA,HADM.FECHA AS FINGRESO, HADM.FECHAALTA AS FEGRESO,HPRED.IDSERVICIO,SER.IDALTERNA,          
  SER.TIPOMED,LEFT(coalesce(SER.DESCSERVICIOCUPS,SER.DESCSERVICIO),60) AS DESCSERVICIO, LEFT(SER.NOM_GENERICO,60) AS NOMGENERICO,          
  HADM.VIAINGRESO, HADM.DXEGRESO AS IDDX, NULL AS TIPODX,          
  HADM.DXEGRESO AS DXSALIDA,HADM.DXSALIDA1 AS DXR1,HADM.DXSALIDA2 AS DXR2,HADM.DXSALIDA3 AS DXR3, HADM.COMPLICACION AS COMPLICACION, '' AS FORMAREALIZACION,           
  HADM.CAUSABMUERTE AS CAUSAMUERTE, HADM.DESTINO AS DESTINO, HADM.ESTADOPSALIDA AS ESTADOSALIDA,           
  CAST(ROUND(abs(COALESCE(HPRED.CANTIDAD,1)),0) AS INT) AS CANTIDAD,           
  round(CAST(abs(COALESCE(HPRED.VALOR,0)) AS DECIMAL(15,2)),0) AS VALOR, round(CAST(abs(COALESCE(HPRED.VALORCOPAGO,0)) AS DECIMAL(15,2)),0) AS VALORCOPAGO,           
  round(CAST(abs(COALESCE(HPRED.VALOR,0))*abs(COALESCE(HPRED.CANTIDAD,1)) AS DECIMAL(15,2)),0) AS VALORITEM,           
  round(CAST(abs((COALESCE(HPRED.VALOR,0)*COALESCE(HPRED.CANTIDAD,1))-COALESCE(HPRED.VALORCOPAGO,0)) AS DECIMAL(15,2)),0) AS VRNETO,          
  CIRUGIA=0,HPRED.IDCIRUGIA,HPRED.CONSECUTIVOCX,HPRED.KCNTRID,HPRED.KCNTID, HPRE.IDSEDE,          
  SER.PREFIJO, SER.IDARTICULO, HPRE.IDMEDICO, HADM.TIPOTTEC, HADM.CAUSAEXTERNA, HPRE.TIPOPRESTACION,           
  HADM.NOAUTORIZACION, HPRE.NUMAUTORIZA, HPRED_NOAUTORIZACION=HPRED.NOAUTORIZACION, HPRE.AMBITO, HADM.DXINGRESO, SER.IDCUM          
 FROM dbo.HPRE           
  JOIN dbo.HPRED ON HPRED.NOPRESTACION = HPRE.NOPRESTACION           
  JOIN dbo.HADM  ON HADM.NOADMISION    = HPRE.NOADMISION           
  JOIN dbo.AFI   ON AFI.IDAFILIADO     = HADM.IDAFILIADO          
  JOIN dbo.SER   ON SER.IDSERVICIO     = HPRED.IDSERVICIO          
  JOIN dbo.RENCP ON RENCP.IDCONCEPTORIPS = SER.CODIGORIPS           
 WHERE HPRE.TIPOPRESTACION = 0 /*AND HPRED.VALOR > 0 */ AND (COALESCE(HPRE.CIRUGIA,'No')<>'Si')          
  AND COALESCE(HADM.CLASENOPROC,'')<>'NP' -- Excluye los No procesar          
  AND NOT (RENCP.ARCHIVO in ('AH','AU') AND HADM.CLASEING<>'A') -- Excluye las que no son del Modulo Hospitalario para AH y AU 
go
