drop PROCEDURE [dbo].[SPK_TRASLADA_HPRE]
go
CREATE PROCEDURE [dbo].[SPK_TRASLADA_HPRE]   
	@NOADMISIONORI VARCHAR(16),  
	@NOADMISIONDES VARCHAR(16),  
	@NOPRESTACION  VARCHAR(16),  
	@USUARIO       VARCHAR(12),  
	@SYS_COMPUTERNAME VARCHAR(254)  
AS  
DECLARE @CIRUGIA     VARCHAR(2)  
DECLARE @CONSECUTIVO VARCHAR(13)  
BEGIN  
	if (select COUNT(*) from HPRED with(nolock) where NOPRESTACION = @NOPRESTACION and FACTURADA = 1) = 0
	begin
	   UPDATE HPRE SET NOADMISION = @NOADMISIONDES  
	   WHERE  NOPRESTACION = @NOPRESTACION  
	   AND    NOADMISION   = @NOADMISIONORI     
     
	   SELECT @CIRUGIA = CIRUGIA, @CONSECUTIVO = CONSECUTIVO FROM HPRE WHERE NOPRESTACION = @NOPRESTACION  
	   -- REVISAMOS SI ES UNA PRESTACION GENERADA POR UNA CIRUGIA  
	   -- PARA TRASLADAR TAMBIEN TODOS LOS DATOS DE LA CIRUGIA  
	   IF @CIRUGIA = 'SI'     
	   BEGIN  
		  UPDATE QXPCX  SET NOADMISION = @NOADMISIONDES WHERE CONSECUTIVO = @CONSECUTIVO  
		  UPDATE QXPCXI SET NOADMISION = @NOADMISIONDES WHERE CONSECUTIVO = @CONSECUTIVO  
		  UPDATE QXPCXR SET NOADMISION = @NOADMISIONDES WHERE CONSECUTIVO = @CONSECUTIVO  
		  UPDATE QXPCXS SET NOADMISION = @NOADMISIONDES WHERE CONSECUTIVO = @CONSECUTIVO  
	   END
	end
	else
		raiserror('No se permite trasladar la prestación %s con items facturados.',16,1,@NOPRESTACION);
END   
go
