drop PROCEDURE if exists [dbo].[SPK_ESTADO_ADMI]
go

-- 20251212: Ya no se valida el valor del copago.
-- Inventario: Oncomedica8 -> DxContable 
-- *Contiene consulta unida de movimientos de ambas BD   
CREATE PROC [dbo].[SPK_ESTADO_ADMI]  
 @NOADMISION VARCHAR(16),  
 @RPDX       VARCHAR(20)  
AS  
DECLARE @CONT                 INT  
DECLARE @COPAGONOAUTORIZACION VARCHAR(20)  
DECLARE @COPAGOVALOR          DECIMAL(14,2)  
DECLARE @VALOR                DECIMAL(14,2)  
DECLARE @NOPRESTACION         VARCHAR(16)  
DECLARE @DATO                 VARCHAR(80)  
BEGIN  
   SELECT @CONT = COALESCE(COUNT(*),0) FROM HPRE WHERE NOADMISION = @NOADMISION  
   IF @CONT = 0  
   BEGIN  
      PRINT 'SIN CARGOS'  
      INSERT INTO RPDX ( CNS, NOMBRE )   
      SELECT @RPDX, 'ADMISION SIN PRESTACIONES (CARGOS)'  
      RETURN  
   END  
   SELECT @COPAGONOAUTORIZACION = COPAGONOAUTORIZACION, @COPAGOVALOR = COPAGOVALOR   
   FROM   HADM  
   WHERE  NOADMISION = @NOADMISION  
     
   PRINT 'MIRAR HPRE SIN HPRED '  
   DECLARE PRESTACIOND_CURSOR CURSOR FOR    
   SELECT NOPRESTACION FROM HPRE WHERE NOADMISION = @NOADMISION  
   OPEN PRESTACIOND_CURSOR    
   FETCH NEXT FROM PRESTACIOND_CURSOR    
   INTO @NOPRESTACION  
   WHILE @@FETCH_STATUS = 0    
   BEGIN          
      SELECT @CONT = COALESCE(COUNT(*),0) FROM HPRED WHERE HPRED.NOPRESTACION = @NOPRESTACION  
      IF @CONT = 0  
      BEGIN  
         INSERT INTO RPDX ( CNS, NOMBRE )   
         SELECT @RPDX, 'PRESTACION '+@NOPRESTACION+' SN DETALLES'           
      END  
      FETCH NEXT FROM PRESTACIOND_CURSOR    
      INTO @NOPRESTACION  
   END  
   CLOSE PRESTACIOND_CURSOR    
   DEALLOCATE PRESTACIOND_CURSOR    
   /*
   PRINT 'REVISION SI TIENE AUTORIZACION LA ADMISION '  
   IF @COPAGONOAUTORIZACION IS NOT NULL AND @COPAGONOAUTORIZACION <> ''  
   BEGIN   
      SELECT @VALOR = SUM(HPRE.VALORCOPAGO) FROM HPRE WHERE NOADMISION = @NOADMISION        
      IF @VALOR <> @COPAGOVALOR  
      BEGIN  
         INSERT INTO RPDX ( CNS, NOMBRE )   
         SELECT @RPDX, 'COPAGO SIN DISTRIBUIR TOTALMENTE'  
      END  
   END    
   */
   PRINT 'CIRUGIA'   
   SELECT @CONT = COALESCE(COUNT(*),0) FROM QXPCX WHERE NOADMISION = @NOADMISION AND LIQ_ADC = 0  
   IF @CONT > 0  
   BEGIN  
      PRINT 'ENTRE A CIRUGIA SIN LIQUIDAR'  
      INSERT INTO RPDX ( CNS, NOMBRE )   
      SELECT @RPDX, 'CIRUGIA SIN LIQUIDAR'  
   END  
   PRINT 'REVISION DE DOCUMENTACION'  
   SELECT @CONT = COALESCE(COUNT(*),0) FROM HREQ WHERE NOADMISION = @NOADMISION AND CUMPLIDO = 0  
   IF @CONT > 0  
   BEGIN  
      INSERT INTO RPDX ( CNS, NOMBRE )   
      SELECT @RPDX, 'DOCUMENTACION INCOMPLETA'  
   END  
   PRINT 'REVISION DE PEDIDOS A INVENTARIO'  
   SELECT @CONT = COALESCE(COUNT(*),0) FROM HPRE WHERE NOADMISION = @NOADMISION AND ESDEINV = 1 AND PEDIDOINV = 0  
   IF @CONT > 0  
   BEGIN  
      INSERT INTO RPDX ( CNS, NOMBRE )   
      SELECT @RPDX, 'CARGOS SIN PEDIR A INVENTARIOS'  
   END  
   PRINT 'REVISA PEDIDOS A INVENTARIOS SIN CONFIRMAR'  
   SELECT @DATO = DATO FROM USVGS WHERE IDVARIABLE = 'PALTASINCONF'  
   IF @DATO <> 'SI'  
   BEGIN  
      SELECT @CONT = COALESCE(COUNT(*),0)   
   from DxContable.dbo.IMOVSS a with(nolock)  
  join DxContable.dbo.IMOV m with(nolock) on a.IDTRANSACCION=m.IDTRANSACCION and a.NUMDOCUMENTO=m.NUMDOCUMENTO   
   and a.PROCEDENCIA = 'SALUD'     
   WHERE a.NOADMISION = @NOADMISION AND m.ESTADO = '0'        
      IF @CONT > 0  
      BEGIN  
         INSERT INTO RPDX ( CNS, NOMBRE )   
         SELECT @RPDX, 'CARGOS SIN CONFIRMAR EN INVENTARIO'  
      END  
   -- Inv.Asistencial  
   SELECT @CONT = COALESCE(COUNT(*),0) FROM IMOV with(nolock) WHERE NODOCUMENTO = @NOADMISION AND ESTADO = '0' and coalesce(PROCESO,'')<>'DOXA_PR'       
      IF @CONT > 0  
      BEGIN  
         INSERT INTO RPDX ( CNS, NOMBRE )   
         SELECT @RPDX, 'CARGOS SIN CONFIRMAR EN INVENTARIO ASISTENCIAL'  
      END  
  
   END  
   PRINT 'REVISA DATOS RECIEN NACIDO'  
   SELECT @CONT = COALESCE(COUNT(*),0)  
   FROM   QXPCX INNER JOIN QXPCXD ON QXPCX.CONSECUTIVO = QXPCXD.CONSECUTIVO  
   WHERE  QXPCX.NOADMISION = @NOADMISION  
   AND    QXPCXD.IDSERVICIO IN (SELECT CODIGO FROM TGEN WHERE TABLA = 'General' AND CAMPO = 'CXCONRNACIDO')  
   IF @CONT > 0  
   BEGIN  
      SELECT @CONT = COALESCE(COUNT(*),0) FROM QXRCN WHERE NOADMISION = @NOADMISION  
      IF @CONT < 1  
      BEGIN  
         INSERT INTO RPDX ( CNS, NOMBRE )   
         SELECT @RPDX, 'SIN REGISTRO DE RECIEN NACIDO'  
      END  
      ELSE  
      BEGIN  
         SELECT @CONT = COUNT(*) FROM QXRCN WHERE NOADMISION = @NOADMISION  
  AND    ((CMPERIODOGES IS NULL OR CMPERIODOGES = '') OR  
                 (CMCONTROLPRE IS NULL OR CMCONTROLPRE = '') OR  
   (RNFECHANACE IS NULL OR RNFECHANACE = '') OR  
                 (RNSEXO IS NULL OR RNSEXO = '') OR  
   (RNPESO IS NULL OR RNPESO = '') OR  
                 (RNTALLA IS NULL OR RNTALLA = '') OR  
                 (RNDX IS NULL OR RNDX = '') OR  
                 (ESTADORN IS NULL OR ESTADORN = '') OR  
                 (RNAPGAR5 IS NULL OR RNAPGAR5 = ''))  
         IF @CONT > 0  
  BEGIN  
            INSERT INTO RPDX ( CNS, NOMBRE )   
            SELECT @RPDX, 'SIN DATOS DE RECIEN NACIDO'  
         END  
      END  
   END  
END  
go