drop view [dbo].[vwa_HADM]
go
Create View [dbo].[vwa_HADM] -- with schemabinding    
as    
 SELECT A.NOADMISION, A.IDAFILIADO, A.FECHA, A.CLASEING, A.IDPLAN, A.IDTERCERO, A.TIPOADM, C.DESCRIPCION, A.HABCAMA, A.VIAINGRESO, A.DXINGRESO, A.FECHAVCEAUT, A.FECHAALTA, A.RESPCUENTA,     
  A.IDMEDICOTRA, A.FACTURADA, A.N_FACTURA, A.CERRADA, A.USUARIO, A.TIPOPOLIZA, A.FACTURABLE, A.COPAGO, A.COPAGONOAUTORIZACION, A.COPAGOVALOR, A.VFACTURAS,     
  A.DESCUENTO, A.TIPODTO, A.USUARIOALTA, A.TIPOCREDITO, A.CREDITO, A.MARCA, A.VENCEAUT, A.MTOPE, A.TIPOTOPE, A.FECHATOPE, A.VALORTOPE, A.TOPEOTROTERCERO,     
  A.IDAREA_ALTA, A.CLASENOPROC, A.LIQESTANCIA, A.FACTURADAPARCIAL, A.CNSHACTRAN, A.IDAREAINGRESO, A.IDAREAACTUAL, B.PAPELLIDO, B.SAPELLIDO,     
  B.PNOMBRE, B.SNOMBRE, B.TIPO_DOC, B.DOCIDAFILIADO, B.IDALTERNA, B.IDAFILIADOPPAL, B.CIUDAD, B.ZONA, B.IDSEDE, B.IDPROVEEDOR, B.IDADMINISTRADORA, B.NUMCARNET     
 FROM  dbo.HADM A     
  join dbo.afi B on A.IDAFILIADO=B.IDAFILIADO     
  join dbo.HTAD C on a.TIPOADM=C.TIPOADM      
 WHERE ( (CERRADA >=0 and CERRADA<= 2) )     
-- ORDER BY  A.CERRADA,  A.NOADMISION DESC    
go
