SELECT  * FROM TGEN WHERE TABLA LIKE '%RIPSJS%' 

INSERT INTO TGEN (TABLA,CAMPO,CODIGO,DESCRIPCION,ESTADO) VALUES ('RIPSJS','RIPSJS','1','Finalizado procedimientos','Activo')
INSERT INTO TGEN (TABLA,CAMPO,CODIGO,DESCRIPCION,ESTADO) VALUES ('RIPSJS','RIPSJS','2','Procesando procedimientos','Activo')
INSERT INTO TGEN (TABLA,CAMPO,CODIGO,DESCRIPCION,ESTADO) VALUES ('RIPSJS','RIPSJS','3','Novedad procedimientos','Activo')
INSERT INTO TGEN (TABLA,CAMPO,CODIGO,DESCRIPCION,ESTADO) VALUES ('RIPSJS','RIPSJS','4','Finalizado Json','Activo')
INSERT INTO TGEN (TABLA,CAMPO,CODIGO,DESCRIPCION,ESTADO) VALUES ('RIPSJS','RIPSJS','5','Procesando Json','Activo')
INSERT INTO TGEN (TABLA,CAMPO,CODIGO,DESCRIPCION,ESTADO) VALUES ('RIPSJS','RIPSJS','6','Novedad Json','Activo')
INSERT INTO TGEN (TABLA,CAMPO,CODIGO,DESCRIPCION,ESTADO) VALUES ('RIPSJS','RIPSJS','7','Finalizado ApiDocker','Activo')
INSERT INTO TGEN (TABLA,CAMPO,CODIGO,DESCRIPCION,ESTADO) VALUES ('RIPSJS','RIPSJS','8','Procesando ApiDocker','Activo')
INSERT INTO TGEN (TABLA,CAMPO,CODIGO,DESCRIPCION,ESTADO) VALUES ('RIPSJS','RIPSJS','9','Novedad ApiDocker','Activo')