-- 23.jul.2025

drop VIEW [dbo].[VW_PRE_HADM]
go
-- 20250723: Se excluyen las FMAS con factura Anuada
CREATE VIEW [dbo].[VW_PRE_HADM]      
AS      
	SELECT FMAS.CNSFMAS, HPRE.NOADMISION, HPRE.NOPRESTACION, PRE.PREFIJO, HPRED.IDSERVICIO, HPRED.VALOR, HPRED.CANTIDAD,      
		vt.VALORTOTAL, VALORCOPAGO = coalesce(HPRED.VALORCOPAGO,0), /*+ cop.COPAGO_DIST*/   
		VALORPCOMP=coalesce(HPRED.VALORPCOMP,0), ve.VALOREXCEDENTE, HPRED.IDCIRUGIA, HPRED.TIPOSERCIRUGIA,  
		NOAUTORIZACION_HADM=HADM.NOAUTORIZACION, NOAUTORIZACION_HPRE=HPRE.NUMAUTORIZA, NOAUTORIZACION_HPRED=HPRED.NOAUTORIZACION,   
		VALORCOPAGO_HADM=coalesce(HADM.COPAGOVALOR,0), HPRED.NOITEM, HPRED.HPREDID, HPRED.CIVA, HPRED.PIVA, HPRED.VIVA  
	FROM HPRED with(nolock)  
		join HPRE with(nolock) on HPRED.NOPRESTACION = HPRE.NOPRESTACION      
		join SER with(nolock) on HPRED.IDSERVICIO = SER.IDSERVICIO  
		join PRE with(nolock) on SER.PREFIJO = PRE.PREFIJO   
		join FMASD with(nolock) on HPRE.NOADMISION = FMASD.NOADMISION  
		join FMAS with(nolock) on FMAS.CNSFMAS = FMASD.CNSFMAS    
		join HADM with(nolock) on HPRE.NOADMISION = HADM.NOADMISION  
		cross apply (select VALORTOTAL = ((coalesce(HPRED.VALOR,0)+coalesce(HPRED.VIVA,0)) * coalesce(HPRED.CANTIDAD,0))) vt  
		--cross apply (select VALORTOTAL = sum(vt.VALORTOTAL) over (partition by HADM.NOADMISION)) th  
		--cross apply (select COPAGO_DIST = case when th.VALORTOTAL=0 then 0 else ((coalesce(HADM.COPAGOVALOR,0) * vt.VALORTOTAL) / th.VALORTOTAL) end) cop  
		cross apply (select VALOREXCEDENTE = vt.VALORTOTAL - coalesce(HPRED.VALORCOPAGO,0) - coalesce(HPRED.VALORPCOMP,0)/*- cop.COPAGO_DIST*/) ve
		left join FTR with(nolock) on FTR.N_FACTURA = FMAS.N_FACTURA
	WHERE coalesce(FTR.ESTADO,'P') != 'A'
go
